export enum Gouvernorat {
  Ariana = 'Ariana',
  Beja = 'Béja',
  BenArous = 'Ben Arous',
  Bizerte = 'Bizerte',
  Gabes = 'Gabès',
  Gafsa = 'Gafsa',
  Jendouba = 'Jendouba',
  Kairouan = 'Kairouan',
  Kasserine = 'Kasserine',
  Kebili = 'Kébili',
  Kef = 'Le Kef',
  Mahdia = 'Mahdia',
  Manouba = 'La Manouba',
  Medenine = 'Médenine',
  Monastir = 'Monastir',
  Nabeul = 'Nabeul',
  Sfax = 'Sfax',
  SidiBouzid = 'Sidi Bouzid',
  Siliana = 'Siliana',
  Sousse = 'Sousse',
  Tataouine = 'Tataouine',
  Tozeur = 'Tozeur',
  Tunis = 'Tunis',
  Zaghouan = 'Zaghouan'
}
